from . import views
from django.urls import path, include
from rest_framework import routers


urlpatterns = [
    path('registerReqUser', views.RegisterReqUserAPIView.as_view(),
         name="registerReqUser"),
    path('registerNutritionistUser', views.RegisterNutritionistUserAPIView.as_view(
    ), name="registerNutritionistUser"),
    path('info/<int:user_id>/', views.AddInformationAPIView.as_view(), name='info'),
    path('login', views.LoginAPIView.as_view(), name="login"),
    path('user', views.AuthUserAPIView.as_view(), name='user'),
    path('nutritionist', views.AuthNutritionistAPIView.as_view(), name='nutritionist'),
    path('userId', views.GetUserIDAPIView.as_view(), name='userId'),
    path('allergies', views.AlergiesDiseasesAPIView.as_view(), name='allergies'),
    path('addallergy', views.AddAllergiesAPIView.as_view(), name='addallergy'),
    path('adddisease', views.AddDiseasesAPIView.as_view(), name='adddisease'),
    path('getallergies', views.getAllergiesAPIView.as_view(), name='getallergies'),
    path('getalldisease', views.getAllDiseasesAPIView.as_view(), name='getalldisease'),
    path('sendverficationcode', views.ForgotPasswordView.as_view(),
         name='sendverficationcode'),
    path('checkVerfCode', views.CheckVerificationCodeAPIView.as_view(),
         name='checkVerfCode'),
    path('restPassword', views.ResetPasswordAPIView.as_view(), name='restPassword'),
    path('edithealth/<int:user_id>/',
         views.EditHealthInformationsAPIView.as_view(), name='edithealth'),
    path('editinfo/<int:user_id>/',
         views.EditUserInformationsAPIView.as_view(), name='edit'),
    path('editNutritionistinfo/<int:user_id>/',
         views.EditNutritionistInfoAPIView.as_view(), name='editNutritionistinfo'),
    path("editpic/<int:user_id>/",
         views.EditProfilePictureAPIView.as_view(), name='editpic'),
    path("editemail/<int:user_id>/",
         views.EditUserEmailAPIView.as_view(), name='editemail'),
    path("logout/<int:id>/", views.logoutAPIView.as_view(), name="logout"),
    path("getAllNutritionist/", views.getALLNutritionistAPIView.as_view(),
         name='getAllNutritionist'),
    path("changeNutritionistRating/<int:user_id>/",
         views.changeNutritionistRatingAPIView.as_view(), name='changeNutritionistRating'),
    path("getHighestNutritionist", views.getHighestNutritionistRatingAPIView.as_view(
    ), name='getHighestNutritionist'),
    path("getNutritionistInformation/<int:user_id>/",
         views.getNutritionistInformationAPIView.as_view(), name='getNutritionistInformation'),
    path("addFavorite/<int:user_id>/",
         views.AddFavoriteNutritionistsAPIView.as_view(), name='addFavorite'),
    path('deleteFavorite/<int:user_id>/',
         views.DeleteFavoriteNutritionistsAPIView.as_view(), name='deleteFavorite'),
    path('getFavorite', views.GetAllFavoriteNutritionistsAPIView.as_view(),
         name='getFavorite'),
    path('getUserInfoChat/<int:user_id>/',
         views.getUserInfoChatAPIView.as_view(), name='getUserInfoChat'),
    path('ChangePassword', views.ChangePasswordAPIView.as_view(),
         name='changePassword'),
]
